---

- name: install pkg
  package:
    name: "{{xinetd_pkg_name}}"
    state: "{{xinetd_pkg_state}}"

- name: service state, enabled
  service:
    name: "{{xinetd_svc_name}}"
    state: "{{xinetd_svc_state}}"
    enabled: "{{xinetd_svc_enabled}}"
  when: xinetd_pkg_state != 'absent'
